/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModeSelector.java
 *
 * Created on Dec 9, 2010, 11:57:58 AM
 */

package render;

/**
 *
 * @author Ilya
 */
public class ModeSelector extends javax.swing.JPanel {

    /** Creates new form ModeSelector */
    public ModeSelector() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    modeCombo = new javax.swing.JComboBox();
    namelabel = new javax.swing.JLabel();
    infoLabel = new javax.swing.JLabel();

    modeCombo.setFont(modeCombo.getFont().deriveFont(modeCombo.getFont().getSize()+7f));
    modeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show Buttons for Chord", "Chord/Bass Progression", "Show Chord for Buttons", " " }));

    namelabel.setLabelFor(modeCombo);
    namelabel.setText("Accordion Tool Options:");

    infoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    infoLabel.setText("info");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(namelabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(modeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(infoLabel)
        .addContainerGap(203, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(namelabel)
        .addComponent(modeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(infoLabel))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  javax.swing.JLabel infoLabel;
  javax.swing.JComboBox modeCombo;
  private javax.swing.JLabel namelabel;
  // End of variables declaration//GEN-END:variables

}
