/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotePicker.java
 *
 * Created on Oct 7, 2010, 3:41:57 PM
 */

package render;

import java.awt.event.ItemEvent;
import javax.swing.JToggleButton;
import music.Note;

/**
 *
 * @author Ilya
 */
public class NotePicker extends javax.swing.JPanel {

    String accStr;
    String noteStr;
    Note note;

    /** Creates new form NotePicker */
    public NotePicker() {
        initComponents();
        noteStr = "C";
        accStr = "";
        note = new Note();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    rootButtonGroup = new javax.swing.ButtonGroup();
    accButtonGroup = new javax.swing.ButtonGroup();
    rootA = new javax.swing.JToggleButton();
    rootB = new javax.swing.JToggleButton();
    rootC = new javax.swing.JToggleButton();
    rootD = new javax.swing.JToggleButton();
    rootE = new javax.swing.JToggleButton();
    rootF = new javax.swing.JToggleButton();
    rootG = new javax.swing.JToggleButton();
    rootFlat = new javax.swing.JToggleButton();
    rootNatural = new javax.swing.JToggleButton();
    rootSharp = new javax.swing.JToggleButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder(getName()));
    setName("Root:"); // NOI18N

    rootButtonGroup.add(rootA);
    rootA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootA.setText("A");
    rootA.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootA.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    rootButtonGroup.add(rootB);
    rootB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootB.setText("B");
    rootB.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootB.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    rootButtonGroup.add(rootC);
    rootC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootC.setSelected(true);
    rootC.setText("C");
    rootC.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootC.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    rootButtonGroup.add(rootD);
    rootD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootD.setText("D");
    rootD.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootD.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    rootButtonGroup.add(rootE);
    rootE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootE.setText("E");
    rootE.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootE.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    rootButtonGroup.add(rootF);
    rootF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootF.setText("F");
    rootF.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootF.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    rootButtonGroup.add(rootG);
    rootG.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootG.setText("G");
    rootG.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootG.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    accButtonGroup.add(rootFlat);
    rootFlat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootFlat.setText("b");
    rootFlat.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootFlat.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    accButtonGroup.add(rootNatural);
    rootNatural.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootNatural.setSelected(true);
    rootNatural.setText("-");
    rootNatural.setActionCommand(" ");
    rootNatural.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootNatural.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    accButtonGroup.add(rootSharp);
    rootSharp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    rootSharp.setText("#");
    rootSharp.setMargin(new java.awt.Insets(2, 8, 2, 8));
    rootSharp.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        NoteItemChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(rootA)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootB)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootC)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootD)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootF)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootG)
        .addGap(41, 41, 41)
        .addComponent(rootFlat)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootNatural)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rootSharp)
        .addContainerGap(12, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rootA)
          .addComponent(rootB)
          .addComponent(rootC)
          .addComponent(rootD)
          .addComponent(rootE)
          .addComponent(rootF)
          .addComponent(rootG)
          .addComponent(rootFlat)
          .addComponent(rootNatural)
          .addComponent(rootSharp))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void NoteItemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NoteItemChanged
      if (evt.getStateChange() != ItemEvent.SELECTED)
      {
        return;
      }

      if (!(evt.getSource() instanceof JToggleButton))
        return;

      JToggleButton but = (JToggleButton)evt.getSource();

      Note oldNote = note;
      
      if (rootButtonGroup.isSelected(but.getModel()))
        noteStr = but.getActionCommand();
      else if (accButtonGroup.isSelected(but.getModel()))
        accStr = but.getActionCommand();
//      else if (but == rootSharp)
//      {
//        if (but.isSelected())
//          rootFlat.setSelected(false);
//
//        accStr = but.getActionCommand();
//      }
//      else if (but == rootFlat)
//      {
//        if (but.isSelected())
//          rootSharp.setSelected(false);
//
//        accStr = but.getActionCommand();
//      }


      this.firePropertyChange("Note", oldNote, Note.fromString(noteStr + accStr));
    }//GEN-LAST:event_NoteItemChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup accButtonGroup;
  private javax.swing.JToggleButton rootA;
  private javax.swing.JToggleButton rootB;
  private javax.swing.ButtonGroup rootButtonGroup;
  private javax.swing.JToggleButton rootC;
  private javax.swing.JToggleButton rootD;
  private javax.swing.JToggleButton rootE;
  private javax.swing.JToggleButton rootF;
  private javax.swing.JToggleButton rootFlat;
  private javax.swing.JToggleButton rootG;
  private javax.swing.JToggleButton rootNatural;
  private javax.swing.JToggleButton rootSharp;
  // End of variables declaration//GEN-END:variables

}
