/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionsDialog.java
 *
 * Created on Oct 13, 2010, 5:09:34 PM
 */
package render;

import java.awt.Component;
import java.awt.Insets;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author Ilya
 */
public class OptionsDialog extends javax.swing.JDialog
{

  /** Creates new form OptionsDialog */
  public OptionsDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();

    String currLook = UIManager.getLookAndFeel().getName();
    UIManager.LookAndFeelInfo lnfs[] = UIManager.getInstalledLookAndFeels();
    for (int i = 0; i < lnfs.length; i++) {
      if (lnfs[i].getName().equals(currLook)) {
        jComboBox1.setSelectedIndex(i);
        break;
      }
    }
  }

  class LnFComboRenderer extends DefaultListCellRenderer
  {

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
    {
      UIManager.LookAndFeelInfo info = (UIManager.LookAndFeelInfo) value;

      return super.getListCellRendererComponent(list, info.getName(), index, isSelected, cellHasFocus);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jComboBox1 = new JComboBox(UIManager.getInstalledLookAndFeels());
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jComboBox1.setName("lookAndFeelCombo"); // NOI18N
    jComboBox1.setRenderer(new LnFComboRenderer());
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jLabel1.setText("L&F:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addContainerGap(269, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
  {//GEN-HEADEREND:event_jComboBox1ActionPerformed
    if (evt.getSource() != jComboBox1) {
      return;
    }

    doChangeLNF = true;
    changeLNF();
  }//GEN-LAST:event_jComboBox1ActionPerformed
  boolean doChangeLNF = false;

  void changeLNF()
  {
    doChangeLNF = false;
    try {
      UIManager.LookAndFeelInfo info =
              (UIManager.LookAndFeelInfo) jComboBox1.getSelectedItem();

      UIManager.setLookAndFeel(info.getClassName());
      util.Main._rootFrame.repaint();
      SwingUtilities.updateComponentTreeUI(this);
      SwingUtilities.updateComponentTreeUI(util.Main._rootFrame);


    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {

      public void run()
      {
        OptionsDialog dialog = new OptionsDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {

          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
