/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SeqPicker.java
 *
 * Created on Jan 14, 2011, 3:29:04 PM
 */
package render;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.DefaultComboBoxModel;
import music.ChordRegistry;
import music.Note;

/**
 *
 * @author Ilya
 */
public class SeqPicker extends javax.swing.JPanel implements PropertyChangeListener
{

  Note rootNote = new Note();
  SeqColumnModel columnModel;

  /** Creates new form SeqPicker */
  public SeqPicker()
  {
    initComponents();

    filterCombo.setModel(new DefaultComboBoxModel(ChordRegistry.mainRegistry().allSeqGroupNames));

    notePickerRoot.addPropertyChangeListener("Note", this);
  }

  public void init(SeqColumnModel model)
  {
    columnModel = model;
    filterCombo.setSelectedIndex(-1);
    filterCombo.setSelectedIndex(0);
  }

  @Override
  public void propertyChange(PropertyChangeEvent evt)
  {
    if (evt.getSource() == notePickerRoot) {
      rootNote = (Note) evt.getNewValue();
    }

    updateModelSeq();
  }

  private void updateModelSeq()
  {
    if (columnModel != null) {
      ChordRegistry.SeqDef seqDef = (ChordRegistry.SeqDef) listSeqs.getSelectedValue();
      if (seqDef != null) {
        columnModel.populateFromText(seqDef.noteSeq, false, rootNote);
      }
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    listSeqs = new javax.swing.JList();
    filterCombo = new javax.swing.JComboBox();
    notePickerRoot = new render.NotePicker();
    labelRoot = new javax.swing.JLabel();

    listSeqs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listSeqsValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(listSeqs);

    filterCombo.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        filterComboItemStateChanged(evt);
      }
    });

    labelRoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelRoot.setText("Starting Note:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(notePickerRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(81, 81, 81)
            .addComponent(filterCombo, 0, 309, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(filterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelRoot)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(notePickerRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void filterComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_filterComboItemStateChanged
    {//GEN-HEADEREND:event_filterComboItemStateChanged
      int index = filterCombo.getSelectedIndex();
      if (index >= 0) {
        listSeqs.setListData(ChordRegistry.mainRegistry().allSeqDefs[index]);
      } else {
        listSeqs.setListData(new Object[0]);
      }
    }//GEN-LAST:event_filterComboItemStateChanged

    private void listSeqsValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_listSeqsValueChanged
    {//GEN-HEADEREND:event_listSeqsValueChanged
      updateModelSeq();
    }//GEN-LAST:event_listSeqsValueChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox filterCombo;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel labelRoot;
  private javax.swing.JList listSeqs;
  private render.NotePicker notePickerRoot;
  // End of variables declaration//GEN-END:variables
}
