/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabPitchDetect.java
 *
 * Created on Nov 25, 2010, 11:49:39 AM
 */
package render;

import java.awt.BorderLayout;
import java.awt.Graphics;
import javax.swing.JPanel;
import music.Note;
import music.ParsedChordDef;
import music.input.PitchDetect;

/**
 *
 * @author Ilya
 */
public class TabPitchDetect extends javax.swing.JPanel implements PitchDetect.PitchUpdater
{

  PitchDetect pitchDetector;
  SeqColumnModel columnModel;
  Note lastNote, newNote;

  /** Creates new form TabPitchDetect */
  public TabPitchDetect()
  {
    initComponents();

    pitchDetector = new PitchDetect();

    JPanel graphPanel = pitchDetector.getGraphPanel();
    graphPanel.setBackground(jPanel1.getBackground());
    this.jPanel1.add(BorderLayout.CENTER, graphPanel);
  }

  public void setSeqColModel(SeqColumnModel model)
  {
    columnModel = model;
  }

  @Override
  public synchronized void newNote(Note note, double freq)
  {
    if (note == null) {
      detectedText.setText("Current Note: Not detected/too noisy");
      return;
    }

    detectedText.setText("Current Note: " + note.toString());

    if ((columnModel != null) && !note.equals(lastNote)) {
      newNote = note;
      repaint();
    }
  }

  @Override
  public synchronized void paint(Graphics g)
  {
    super.paint(g);
    
    if ((newNote != null) && !newNote.equals(lastNote)) {
      columnModel.editSelectedColumn(new ParsedChordDef(newNote));
      lastNote = newNote;
    }
  }

  @Override
  public void setVisible(boolean visible)
  {
    super.setVisible(visible);

    if (visible) {
      detectedText.setText("Current Note: Not detected/too noisy");
    } else {
      if (pitchDetector.isRunning()) {
        togglePitchDetect();
      }
    }
  }

  void togglePitchDetect()
  {
    if (pitchDetector.isRunning()) {
      toggleDetect.setText("Start Detecting");
      pitchDetector.stop();
    } else {
      toggleDetect.setText("Stop Detecting");
      pitchDetector.start(this);
    }
  }



  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    toggleDetect = new javax.swing.JButton();
    detectedText = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();

    toggleDetect.setText("Start Pitch Detect");
    toggleDetect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        toggleDetectActionPerformed(evt);
      }
    });

    detectedText.setText("jLabel1");

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel1.setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
          .addComponent(toggleDetect)
          .addComponent(detectedText))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(toggleDetect)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(detectedText)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void toggleDetectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggleDetectActionPerformed
  {//GEN-HEADEREND:event_toggleDetectActionPerformed
    // TODO add your handling code here:
    this.togglePitchDetect();
  }//GEN-LAST:event_toggleDetectActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel detectedText;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton toggleDetect;
  // End of variables declaration//GEN-END:variables
}
