/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TextParserPanel.java
 *
 * Created on Oct 21, 2010, 8:29:48 PM
 */
package render;

import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Ilya
 */
public class TextParserPanel extends javax.swing.JPanel implements ListSelectionListener
{

  SeqColumnModel columnModel;
  JTable seqTable;

  /** Creates new form TextParserPanel */
  public TextParserPanel()
  {
    initComponents();
  }

  void setSeqColModel(SeqColumnModel theModel, JTable theTable, String startChords)
  {
    columnModel = theModel;
    seqTable = theTable;
    columnModel.selComboModel.addListSelectionListener(this);
    if (startChords != null) {
      chordTextField.setText(startChords);
      computeButton.doClick();
    }
  }

  @Override
  public void valueChanged(ListSelectionEvent e)
  {
    if (isVisible() && (columnModel != null)) {
      this.chordTextField.setText(columnModel.toString());
    }
  }

  @Override
  public void setVisible(boolean visible)
  {
    if (visible && (columnModel != null)) {
      this.chordTextField.setText(columnModel.toString());
    }
    super.setVisible(visible);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    computeButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    chordTextField = new javax.swing.JTextField();

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chord Sequence Editor:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

    computeButton.setText("Update Chord Sequence");
    computeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        computeButtonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setText("<html>\n<li>Enter a sequence of comma seperated chords  as text below</li><br/>\n<li>See Chord Editor tab for all valid chord names. (ex. M = Major, m = minor)</li><br/>\n<li>To specify a custom chord by notes, put the notes in [ ], (ex. [ABC], [D F# G])</li><br/>\n</html>");
    jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Chord Sequence Below:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

    chordTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    chordTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chordTextFieldActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(chordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(chordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(111, 111, 111)
            .addComponent(computeButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(1, 1, 1)
        .addComponent(computeButton)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_computeButtonActionPerformed
    {//GEN-HEADEREND:event_computeButtonActionPerformed
      String text = chordTextField.getText();
      if (text == null || text.length() == 0)
        text = "C";

      if (columnModel != null) {
        columnModel.populateFromText(text);
      }
      seqTable.requestFocusInWindow();
}//GEN-LAST:event_computeButtonActionPerformed

    private void chordTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chordTextFieldActionPerformed
    {//GEN-HEADEREND:event_chordTextFieldActionPerformed
      this.computeButton.doClick();
    }//GEN-LAST:event_chordTextFieldActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField chordTextField;
  private javax.swing.JButton computeButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
