/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccordionBoardViewer.java
 *
 * Created on Jan 10, 2011, 6:04:22 PM
 */
package app;

import java.awt.Graphics;
import java.util.Vector;
import javax.swing.JApplet;
import music.BoardRegistry;
import music.BoardRegistry.BoardDef;
import render.BoardMouseListener;
import render.RenderBassBoard;
import render.RenderBoardHeader;
import render.SoundController;

/**
 *
 * @author Ilya
 */
public class AccordionBoardViewer extends JApplet
{

  SoundController sound;
  AppletController controller;

  public void init()
  {
    util.Main.setNimbus();

    try {
      java.awt.EventQueue.invokeAndWait(new Runnable()
      {

        public void run()
        {
          initComponents();
          initClientApplet();
        }
      });
    } catch (Exception ex) {
      ex.printStackTrace();
    }
  }

  protected void initClientApplet()
  {
    controller = new AppletController(this);

    RenderBassBoard renderBoard = RenderBassBoard.getStaticRenderBoard();

    sound = new SoundController(false);
    sound.setEnabled(checkSoundEnabled.isSelected());

    Vector<BoardDef> allowedBoards = BoardRegistry.mainRegistry().getStandardBoards();

    BoardMouseListener mouseListener = new BoardMouseListener(renderBoard, null, sound);

    RenderBoardHeader header = this.renderBoardControl.getHeader();
    header.initBoardHeader(renderBoard, renderBoardControl, null, allowedBoards);
    header.selectFirstBoardByBassCount(48);

    header.getExtPanel().add(checkSoundEnabled);
    header.getExtPanel().add(checkVertical);
  }

  /** This method is called from within the init() method to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    checkSoundEnabled = new javax.swing.JCheckBox();
    checkVertical = new javax.swing.JCheckBox();
    renderBoardControl = new render.RenderBoardControl();

    checkSoundEnabled.setFont(new java.awt.Font("Tahoma", 0, 18));
    checkSoundEnabled.setText("Enable Sound");
    checkSoundEnabled.setMargin(new java.awt.Insets(2, 2, 2, 10));
    checkSoundEnabled.setOpaque(false);
    checkSoundEnabled.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        checkSoundEnabledActionPerformed(evt);
      }
    });

    checkVertical.setFont(new java.awt.Font("Tahoma", 0, 18));
    checkVertical.setText("Display Vertically");
    checkVertical.setMargin(new java.awt.Insets(2, 2, 2, 10));
    checkVertical.setOpaque(false);
    checkVertical.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        checkVerticalActionPerformed(evt);
      }
    });

    setName("Accordion Bass Board"); // NOI18N
    getContentPane().add(renderBoardControl, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void checkSoundEnabledActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkSoundEnabledActionPerformed
  {//GEN-HEADEREND:event_checkSoundEnabledActionPerformed
    sound.setEnabled(checkSoundEnabled.isSelected());
  }//GEN-LAST:event_checkSoundEnabledActionPerformed

  private void checkVerticalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkVerticalActionPerformed
  {//GEN-HEADEREND:event_checkVerticalActionPerformed
    this.renderBoardControl.toggleOrientation(!checkVertical.isSelected());
    if (controller.frame.isVisible()) {
      controller.frame.pack();
    }
    this.renderBoardControl.revalidate();
  }//GEN-LAST:event_checkVerticalActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkSoundEnabled;
  private javax.swing.JCheckBox checkVertical;
  private render.RenderBoardControl renderBoardControl;
  // End of variables declaration//GEN-END:variables
}
